apiVersion: v1
kind: Secret
metadata:
  name: mcp-api-key-standard-user
  namespace: kuadrant-system
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: mcp-demo
  annotations:
    kuadrant.io/groups: mcp-user
    secret.kuadrant.io/user-id: mcp-standard-1
stringData:
  api_key: iamamcpuser
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: mcp-api-key-admin-user
  namespace: kuadrant-system
  labels:
    authorino.kuadrant.io/managed-by: authorino
    app: mcp-demo
  annotations:
    kuadrant.io/groups: mcp-user,mcp-admin
    secret.kuadrant.io/user-id: mcp-admin-1
stringData:
  api_key: iamamcpadmin
type: Opaque
